### ISSUE TITLE
前端的更新，部署和bug

### ISSUE THREAD

**Issue by lrq619** [A-Soul-Database/A-Soul-Database#20]
发现了任何前端更新上的不及时，部署上的困难以及bug都可以在这里提出并讨论哦。

**Comment by peterpei1186861238** [comment]
一个想法，不一定对
`https://www.bilibili.com/BVxxxxx?p=2&t=900`
p : 分P
t : 时间（秒
是否可以做跳转🤔

**Comment by lrq619** [comment]
> 一个想法，不一定对
> `https://www.bilibili.com/BVxxxxx?p=2&t=900`
> p : 分P
> t : 时间（秒
> 是否可以做跳转🤔

还真可以，那么是给字幕的时间轴加上超链接吗

**Comment by peterpei1186861238** [comment]
还真是，比如说跳舞唱歌啥的我感觉可以

**Comment by xianzheTM** [comment]
我遇到了部署上的问题。按照readme教程启动后，点击主页的两个快捷方式后都是报错。
以“进入视频库”快捷方式为例：
![image](https://user-images.githubusercontent.com/25103583/131967767-ba615f23-3ffe-45f2-b04c-66e0c1b6930e.png)
此外，从侧边栏进入视频库出现如下错误：
![image](https://user-images.githubusercontent.com/25103583/131968275-4e899588-6165-4051-804e-debc2abdd0e7.png)

**Comment by lrq619** [comment]
> 我遇到了部署上的问题。按照readme教程启动后，点击主页的两个快捷方式后都是报错。
> 以“进入视频库”快捷方式为例：
> ![image](https://user-images.githubusercontent.com/25103583/131967767-ba615f23-3ffe-45f2-b04c-66e0c1b6930e.png)
> 此外，从侧边栏进入视频库出现如下错误：
> ![image](https://user-images.githubusercontent.com/25103583/131968275-4e899588-6165-4051-804e-debc2abdd0e7.png)

1.侧边栏进入网页问题解决：是的，确实会报错，这是因为前端网页从asoulfan.com拿取json数据，而asoulfan.com禁止了跨域请求。
修复此问题的方法：本地调试时将public/js/basic.js中的urlChoice由2修改为1，如下图所示
<img width="566" alt="15adf3139d554c0f8d768b8229d3df6" src="https://user-images.githubusercontent.com/58351056/131969302-adf351ab-11d3-47b5-8647-98c52f1f708c.png">
修改之后拿取json数据的网页将改为rawgithub，不会出现跨域问题。
2.主页两个button超链接会在本地报错但在服务器上正常运行，目前还没解决，本地调试时建议先从侧边栏进入
若能修复这个问题我感激不尽

**Comment by xianzheTM** [comment]
> 
> 
> > 我遇到了部署上的问题。按照readme教程启动后，点击主页的两个快捷方式后都是报错。
> > 以“进入视频库”快捷方式为例：
> > ![image](https://user-images.githubusercontent.com/25103583/131967767-ba615f23-3ffe-45f2-b04c-66e0c1b6930e.png)
> > 此外，从侧边栏进入视频库出现如下错误：
> > ![image](https://user-images.githubusercontent.com/25103583/131968275-4e899588-6165-4051-804e-debc2abdd0e7.png)
> 
> 1.侧边栏进入网页问题解决：是的，确实会报错，这是因为前端网页从asoulfan.com拿取json数据，而asoulfan.com禁止了跨域请求。
> 修复此问题的方法：本地调试时将public/js/basic.js中的urlChoice由2修改为1，如下图所示
> <img alt="15adf3139d554c0f8d768b8229d3df6" width="566" src="https://user-images.githubusercontent.com/58351056/131969302-adf351ab-11d3-47b5-8647-98c52f1f708c.png">
> 修改之后拿取json数据的网页将改为rawgithub，不会出现跨域问题。
> 2.主页两个button超链接会在本地报错但在服务器上正常运行，目前还没解决，本地调试时建议先从侧边栏进入
> 若能修复这个问题我感激不尽

侧边栏访问我是在basic.js中添加localhost。我建议这里使用环境变量设置urlChoice值。而我自己是用docker起的nginx，然后访问web和db文件夹。dockerfile如下：

```
FROM nginx

COPY . ./data
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```
nginx.conf如下：
```
server {
  listen       80;

  location /{
    root /data/web;
    try_files $uri /index.html =404;
  }

  location /db/{
    alias /data/db/;
  }
}
```
如果使用docker部署，理想情况下，只需要clone项目，用dockerfile build镜像，然后启动时传入相应的环境变量即可。不过，另一个问题是，现有的web文件夹直接copy到镜像中能否work我不确定，可能需要cnpm build后的新web文件？前端小白不懂。。

**Comment by xianzheTM** [comment]
主页问题我请教了下公司的前端，改了一下，我本地能正常work了：
![image](https://user-images.githubusercontent.com/25103583/131976350-bcb8e4ea-0eb8-4a7f-b57e-e6e67d74b488.png)
只是改了make-front-end/src/pages/Index/index.jsx中两个button的href

**Comment by lrq619** [comment]
> 主页问题我请教了下公司的前端，改了一下，我本地能正常work了：
> ![image](https://user-images.githubusercontent.com/25103583/131976350-bcb8e4ea-0eb8-4a7f-b57e-e6e67d74b488.png)
> 只是改了make-front-end/src/pages/Index/index.jsx中两个button的href

如果我没有记错的话。。。我原本就是用的这个href，但它在本地不报错的同时，会导致生成的静态文件出现错误。总之似乎这俩（指browser模式和hash模式）总有一个会出问题。我将在今天晚上试一下你的这个href在服务器上会怎样。感谢你的建议

**Comment by lrq619** [comment]
> 我这边反馈是新版字幕库打不开，本地build了复现问题，网络连接正常

确实是寄了，我的代码鲁棒性有点差啊。。。
造成bug的原因是：searchJson这个文件没有更新最新一天的视频数据，bv号：BV1dv411w7ZT。
我会改一下搜索的逻辑，防止以后这种小问题造成网站崩溃

**Comment by lrq619** [comment]
> 我这边反馈是新版字幕库打不开，本地build了复现问题，网络连接正常

逻辑改好了捏，但是searchJson的数据还是需要修复的哦，不然无法在字幕库的搜索栏搜索到它

**Comment by peterpei1186861238** [comment]
多谢，我白天fix，中秋节快乐

**Comment by peterpei1186861238** [comment]
![图片](https://user-images.githubusercontent.com/32994395/134275890-202d5cf8-c700-4c3f-895e-ca92993b3b9e.png)
这俩字幕昨天就跟着上传了.....今天看看试试吧，我怕不是这俩字幕的问题

**Comment by lrq619** [comment]
> ![图片](https://user-images.githubusercontent.com/32994395/134275890-202d5cf8-c700-4c3f-895e-ca92993b3b9e.png)
> 这俩字幕昨天就跟着上传了.....今天看看试试吧，我怕不是这俩字幕的问题

不是字幕，是searchJson那个文件

**Comment by peterpei1186861238** [comment]
对前端改动了两个地方
第一个是昨天然比直播加入了蓝色常服 ，暂时命名成 `DianaOfficialBlue`
第二个是增加了jsdelivr 的源，他是加速GitHub的 🥰

**Comment by peterpei1186861238** [comment]
这几天已经部署了 GitHub Actions 的自动编译项目，以后只需要Push 源代码就可以了捏🥰🥰

**Comment by lrq619** [comment]
> ![图片](https://user-images.githubusercontent.com/32994395/137492066-b4c2a7a2-cbca-4c88-acc4-4829f3c66a69.png) 全新团服捏🥰🥰🥰🥰

我超，你来定中文名和英文名吧，我去插入到字典里

**Comment by peterpei1186861238** [comment]
既然在南京的话就叫 金陵 好了  `JinLing`
现在自动编译这块我还在加功能，现在还得手动编译一下，然后我前几天想着整理一下目录，把他们从`./`移到`./webs`就寄了，可能路径这块还是有点小问题。辛苦了捏🥰🥰🥰🥰

**Comment by xianzheTM** [comment]
我超，加班上线错过了
