### ISSUE TITLE
[疑问]Asoul二创切片的有力助手，免费且开源

### ISSUE THREAD

**Issue by wanghaisheng** [A-Soul-Database/A-Soul-Database#30]
首页我看到这么一句话  二创切片是啥子意思

**Comment by lrq619** [comment]
> 首页我看到这么一句话 二创切片是啥子意思

二创/切片

**Comment by P-PPPP** [comment]
二创: 在设定下进行二次创作，部分二创画面基于直播视频，**但是视频内容和直播可能无关**。 例如:[【A-SOUL】反 转 入 脑 联 盟](https://www.bilibili.com/video/BV1TV411H7uf)

切片: 单独提取某个直播片段，内容紧扣直播。例如： [女孩子说这种话不是让你（）的~](https://www.bilibili.com/video/BV1gr4y1D7Ch)
