### ISSUE TITLE
asdb.live全部数据加载失败

### ISSUE THREAD

**Issue by 1834423612** [A-Soul-Database/A-Soul-Database#32]
访问站点视频库界面一直长时间加载，怀疑有数据传输不正确，经使用F12开发者工具查看网络发现main.json的文件404错误，访问所请求的vercel预览域名下的main.json 404报错，请尽快更换文件源。

![image](https://user-images.githubusercontent.com/49981661/212525673-17ef42dc-aa9e-441c-9cd0-52bbdfadb67a.png)
![image](https://user-images.githubusercontent.com/49981661/212525782-7a23a5c6-1e2d-4630-a95f-b507481a4b8a.png)

**Comment by zhng1456** [comment]
我也一直没进去，不知道还有没有在维护

**Comment by 1834423612** [comment]
> 我也一直没进去，不知道还有没有在维护

可能开发者忘记维护了😂😂😂

**Comment by lrq619** [comment]
> 访问站点视频库界面一直长时间加载，怀疑有数据传输不正确，经使用F12开发者工具查看网络发现main.json的文件404错误，访问所请求的vercel预览域名下的main.json 404报错，请尽快更换文件源。
> 
> ![image](https://user-images.githubusercontent.com/49981661/212525673-17ef42dc-aa9e-441c-9cd0-52bbdfadb67a.png) ![image](https://user-images.githubusercontent.com/49981661/212525782-7a23a5c6-1e2d-4630-a95f-b507481a4b8a.png)

你好，由于CDN到期，ASDB的视频库以及字幕库已经停止维护，感谢您的支持
